import type { Cluster, ClusterId, Project } from './types';

export const CLUSTERS: Cluster[] = [
  {
    id: 'business-model',
    name: 'Business Model Development & Circular Economy Strategy',
    short: 'Business Model',
    purpose:
      'Circular economy business model development and strategic planning to scale sustainable innovations from prototype to implementation.',
    connectsTo: ['platform', 'lca', 'product-design'],
  },
  {
    id: 'platform',
    name: 'Platform Development',
    short: 'Platform',
    purpose:
      'Full-stack platform to scale prototypes to a production-ready application including finance strategy and policy within a circular-economy framework.',
    connectsTo: ['business-model', 'lca', 'mbse', 'biomedical'],
  },
  {
    id: 'lca',
    name: 'Life Cycle Assessment',
    short: 'LCA',
    purpose:
      'PLM & LCA as a decision-making tool for sustainable products and processes.',
    connectsTo: ['bio-materials', 'product-design', 'mbse', 'platform'],
  },
  {
    id: 'mbse',
    name: 'Model-Based Systems Engineering',
    short: 'MBSE',
    purpose:
      'MBSE is the main structure where all clusters connect on digital models instead of traditional documentation.',
    connectsTo: ['platform', 'lca', 'product-design', 'biomedical', 'bio-materials'],
  },
  {
    id: 'bio-materials',
    name: 'Bio-based and Compostable Materials',
    short: 'Bio-Materials',
    purpose:
      'Bio-based home compostable material development, characterisation and end-of-life validation.',
    connectsTo: ['lca', 'product-design', 'mbse'],
  },
  {
    id: 'product-design',
    name: 'Product Design & Product Manufacturing',
    short: 'Product Design',
    purpose:
      'Fully compostable bottle — parameterized concept/CAD to pilot prototype.',
    connectsTo: ['bio-materials', 'lca', 'business-model', 'mbse'],
  },
  {
    id: 'biomedical',
    name: 'Biomedical Applications',
    short: 'Biomedical',
    purpose:
      'Low-cost diagnostic device for disease biomarker detection.',
    connectsTo: ['platform', 'mbse'],
  },
];

export const CLUSTER_BY_ID = Object.fromEntries(CLUSTERS.map((c) => [c.id, c])) as Record<ClusterId, Cluster>;

const today = '2026-09-25';

export const PROJECTS: Project[] = [
  {
    id: 'p-bio-pha',
    slug: 'home-compostable-pha-film',
    name: 'Home-Compostable PHA Film',
    cluster: 'bio-materials',
    category: 'Materials R&D',
    organization: 'I2CE Lab',
    team: ['Materials', 'Characterisation'],
    status: 'Prototype',
    accent: '#3ef08a',
    description:
      'Bio-based PHA blend developed for home-compostable packaging film, characterised by confocal and SEM area-scan mapping to confirm dispersion and disintegration behaviour.',
    startDate: '2025-08-01',
    updatedAt: today,
    confidence: 'measured',
    materials: { primaryMaterial: 'PHA / cellulose blend', quantityKg: 4200, recycledPct: 8, renewablePct: 92, bioBasedPct: 88, reusablePct: 12, recyclablePct: 35 },
    waste: { totalInputKg: 4200, manufacturingWasteKg: 520, reusedInternallyKg: 190, recycledExternallyKg: 95, landfillKg: 235, hazardousKg: 4, packagingWasteKg: 60 },
    lifecycle: { expectedLifeYears: 1, repairability: 5, modularity: 10, reusability: 15, remanufacturability: 10, recoveryRatePct: 78, takeBackProgram: false },
    financials: { materialCost: 310000, wasteDisposalCost: 24000, productionCost: 480000, reuseSavings: 46000, recyclingSavings: 18000, circularRevenue: 62000, circularInvestment: 240000, discountRate: 0.1, horizonYears: 7 },
    environmental: { carbonFootprintTco2e: 310, carbonReductionTco2e: 190, waterUsageM3: 5400, waterSavingsM3: 1800, energyUsageMwh: 820, energySavingsMwh: 210, renewableEnergyPct: 38 },
    products: [
      { id: 'pr-film', slug: 'compostable-barrier-film', name: 'Compostable Barrier Film', description: 'Single-layer home-compostable barrier film for dry-goods packaging.', endOfLife: 'Home compost bin. Disintegrates within 26 weeks at ambient temperature; no industrial facility required.', repairNotes: 'Not repairable. Offcuts and trim are regrind-compatible and should be returned to the production line, not binned.' },
    ],
  },
  {
    id: 'p-bottle',
    slug: 'fully-compostable-bottle',
    name: 'Fully Compostable Bottle',
    cluster: 'product-design',
    category: 'Product Design',
    organization: 'I2CE Lab',
    team: ['CAD', 'Tooling', 'Pilot Line'],
    status: 'Pilot',
    accent: '#4fd6ff',
    description:
      'Parameterized bottle concept taken from CAD family through injection/blow tooling to a pilot prototype, with body height and body diameter as the driving parameters.',
    startDate: '2025-05-15',
    updatedAt: today,
    confidence: 'measured',
    materials: { primaryMaterial: 'PLA/PHA copolymer', quantityKg: 9800, recycledPct: 22, renewablePct: 86, bioBasedPct: 82, reusablePct: 30, recyclablePct: 55 },
    waste: { totalInputKg: 9800, manufacturingWasteKg: 1180, reusedInternallyKg: 690, recycledExternallyKg: 240, landfillKg: 250, hazardousKg: 0, packagingWasteKg: 140 },
    lifecycle: { expectedLifeYears: 2, repairability: 20, modularity: 45, reusability: 55, remanufacturability: 35, recoveryRatePct: 64, takeBackProgram: true },
    financials: { materialCost: 720000, wasteDisposalCost: 51000, productionCost: 1240000, reuseSavings: 158000, recyclingSavings: 64000, circularRevenue: 145000, circularInvestment: 680000, discountRate: 0.1, horizonYears: 7 },
    environmental: { carbonFootprintTco2e: 940, carbonReductionTco2e: 610, waterUsageM3: 14200, waterSavingsM3: 5100, energyUsageMwh: 2100, energySavingsMwh: 640, renewableEnergyPct: 52 },
    products: [
      { id: 'pr-bottle', slug: 'parametric-compostable-bottle', name: 'Parametric Compostable Bottle 500ml', description: 'Pilot-tooled 500 ml compostable bottle, one member of a parameterized CAD family spanning 250–1000 ml.', endOfLife: 'Return through the take-back programme, or home compost after cap separation. Cap is a separate material and must be removed.', repairNotes: 'Cap and sleeve are user-replaceable. Body is single-material by design so no separation step is needed at recovery.' },
    ],
  },
  {
    id: 'p-diagnostic',
    slug: 'low-cost-biomarker-device',
    name: 'Low-Cost Biomarker Diagnostic Device',
    cluster: 'biomedical',
    category: 'Biomedical Device',
    organization: 'I2CE Lab',
    team: ['Device', 'Firmware', 'Assay'],
    status: 'Prototype',
    accent: '#7dffb0',
    description:
      'Low-cost reader and disposable test strip for disease biomarker detection, with a companion app reporting glucose, ketone and protein markers against reference ranges.',
    startDate: '2025-09-10',
    updatedAt: today,
    confidence: 'estimated',
    materials: { primaryMaterial: 'ABS housing + PCB + paper strip', quantityKg: 1600, recycledPct: 34, renewablePct: 18, bioBasedPct: 12, reusablePct: 68, recyclablePct: 72 },
    waste: { totalInputKg: 1600, manufacturingWasteKg: 210, reusedInternallyKg: 55, recycledExternallyKg: 90, landfillKg: 65, hazardousKg: 12, packagingWasteKg: 48 },
    lifecycle: { expectedLifeYears: 6, repairability: 62, modularity: 70, reusability: 80, remanufacturability: 58, recoveryRatePct: 45, takeBackProgram: false },
    financials: { materialCost: 260000, wasteDisposalCost: 31000, productionCost: 590000, reuseSavings: 72000, recyclingSavings: 26000, circularRevenue: 38000, circularInvestment: 320000, discountRate: 0.12, horizonYears: 7 },
    environmental: { carbonFootprintTco2e: 420, carbonReductionTco2e: 130, waterUsageM3: 3100, waterSavingsM3: 620, energyUsageMwh: 690, energySavingsMwh: 120, renewableEnergyPct: 30 },
    products: [
      { id: 'pr-reader', slug: 'biomarker-reader', name: 'Biomarker Reader Unit', description: 'Reusable optical reader with a six-year design life and replaceable battery pack.', endOfLife: 'Reader is WEEE electronics — return to the lab or an electronics recovery point. Do not bin with household waste.', repairNotes: 'Battery pack and optical window are field-replaceable with a single driver. Firmware is updatable over USB-C.' },
      { id: 'pr-strip', slug: 'biomarker-test-strip', name: 'Disposable Test Strip', description: 'Paper-based single-use assay strip with a printed reagent pad.', endOfLife: 'Used strips are clinical waste. Unused strips are paper-recyclable after removing the foil pouch.', repairNotes: 'Single use by design. Not repairable.' },
    ],
  },
  {
    id: 'p-lca',
    slug: 'plm-lca-decision-engine',
    name: 'PLM + LCA Decision Engine',
    cluster: 'lca',
    category: 'Assessment Infrastructure',
    organization: 'I2CE Lab',
    team: ['LCA', 'PLM', 'Data'],
    status: 'Scaling',
    accent: '#19bdf0',
    description:
      'Life-cycle assessment wired directly into product lifecycle management so that material and process choices are scored at the point the decision is made, not audited a year later.',
    startDate: '2025-02-01',
    updatedAt: today,
    confidence: 'measured',
    materials: { primaryMaterial: 'n/a — assessment infrastructure', quantityKg: 0, recycledPct: 0, renewablePct: 0, bioBasedPct: 0, reusablePct: 0, recyclablePct: 0 },
    waste: { totalInputKg: 1, manufacturingWasteKg: 0, reusedInternallyKg: 0, recycledExternallyKg: 0, landfillKg: 0, hazardousKg: 0, packagingWasteKg: 0 },
    lifecycle: { expectedLifeYears: 8, repairability: 85, modularity: 90, reusability: 88, remanufacturability: 70, recoveryRatePct: 0, takeBackProgram: false },
    financials: { materialCost: 0, wasteDisposalCost: 0, productionCost: 340000, reuseSavings: 0, recyclingSavings: 0, circularRevenue: 210000, circularInvestment: 190000, discountRate: 0.1, horizonYears: 7 },
    environmental: { carbonFootprintTco2e: 40, carbonReductionTco2e: 980, waterUsageM3: 200, waterSavingsM3: 4200, energyUsageMwh: 90, energySavingsMwh: 510, renewableEnergyPct: 74 },
    products: [],
  },
  {
    id: 'p-mbse',
    slug: 'mbse-digital-thread',
    name: 'MBSE Digital Thread',
    cluster: 'mbse',
    category: 'Systems Engineering',
    organization: 'I2CE Lab',
    team: ['Systems', 'Architecture'],
    status: 'Scaling',
    accent: '#ffc857',
    description:
      'The connective structure of the programme: every cluster publishes into a shared system model so requirements, material data and lifecycle results stay one artefact rather than seven documents.',
    startDate: '2025-01-15',
    updatedAt: today,
    confidence: 'measured',
    materials: { primaryMaterial: 'n/a — systems model', quantityKg: 0, recycledPct: 0, renewablePct: 0, bioBasedPct: 0, reusablePct: 0, recyclablePct: 0 },
    waste: { totalInputKg: 1, manufacturingWasteKg: 0, reusedInternallyKg: 0, recycledExternallyKg: 0, landfillKg: 0, hazardousKg: 0, packagingWasteKg: 0 },
    lifecycle: { expectedLifeYears: 10, repairability: 90, modularity: 95, reusability: 92, remanufacturability: 80, recoveryRatePct: 0, takeBackProgram: false },
    financials: { materialCost: 0, wasteDisposalCost: 0, productionCost: 280000, reuseSavings: 0, recyclingSavings: 0, circularRevenue: 160000, circularInvestment: 150000, discountRate: 0.1, horizonYears: 7 },
    environmental: { carbonFootprintTco2e: 30, carbonReductionTco2e: 420, waterUsageM3: 120, waterSavingsM3: 900, energyUsageMwh: 70, energySavingsMwh: 180, renewableEnergyPct: 74 },
    products: [],
  },
  {
    id: 'p-platform',
    slug: 'tokuma-platform',
    name: 'Tokuma Platform',
    cluster: 'platform',
    category: 'Software Platform',
    organization: 'I2CE Lab',
    team: ['Full-stack', 'Data', 'Finance Strategy'],
    status: 'Production',
    accent: '#3ef08a',
    description:
      'The full-stack platform this dashboard runs on: scores industrial waste streams, translates the result into investor-relevant financial metrics, and publishes a public transparency page per product.',
    startDate: '2025-06-01',
    updatedAt: today,
    confidence: 'measured',
    materials: { primaryMaterial: 'n/a — software', quantityKg: 0, recycledPct: 0, renewablePct: 0, bioBasedPct: 0, reusablePct: 0, recyclablePct: 0 },
    waste: { totalInputKg: 1, manufacturingWasteKg: 0, reusedInternallyKg: 0, recycledExternallyKg: 0, landfillKg: 0, hazardousKg: 0, packagingWasteKg: 0 },
    lifecycle: { expectedLifeYears: 8, repairability: 88, modularity: 92, reusability: 90, remanufacturability: 75, recoveryRatePct: 0, takeBackProgram: false },
    financials: { materialCost: 0, wasteDisposalCost: 0, productionCost: 420000, reuseSavings: 0, recyclingSavings: 0, circularRevenue: 380000, circularInvestment: 260000, discountRate: 0.1, horizonYears: 7 },
    environmental: { carbonFootprintTco2e: 25, carbonReductionTco2e: 1450, waterUsageM3: 90, waterSavingsM3: 6200, energyUsageMwh: 60, energySavingsMwh: 740, renewableEnergyPct: 80 },
    products: [],
  },
  {
    id: 'p-business',
    slug: 'circular-business-model-scaling',
    name: 'Circular Business Model Scaling',
    cluster: 'business-model',
    category: 'Strategy & Finance',
    organization: 'I2CE Lab',
    team: ['Strategy', 'Finance', 'Policy'],
    status: 'Scaling',
    accent: '#ff6b81',
    description:
      'Business-model and capital strategy that takes a validated prototype and answers the question an investor actually asks: what does this return, over what horizon, at what capital requirement.',
    startDate: '2025-03-01',
    updatedAt: today,
    confidence: 'estimated',
    materials: { primaryMaterial: 'n/a — strategy', quantityKg: 0, recycledPct: 0, renewablePct: 0, bioBasedPct: 0, reusablePct: 0, recyclablePct: 0 },
    waste: { totalInputKg: 1, manufacturingWasteKg: 0, reusedInternallyKg: 0, recycledExternallyKg: 0, landfillKg: 0, hazardousKg: 0, packagingWasteKg: 0 },
    lifecycle: { expectedLifeYears: 7, repairability: 70, modularity: 75, reusability: 70, remanufacturability: 60, recoveryRatePct: 0, takeBackProgram: false },
    financials: { materialCost: 0, wasteDisposalCost: 0, productionCost: 210000, reuseSavings: 0, recyclingSavings: 0, circularRevenue: 240000, circularInvestment: 140000, discountRate: 0.14, horizonYears: 7 },
    environmental: { carbonFootprintTco2e: 15, carbonReductionTco2e: 260, waterUsageM3: 50, waterSavingsM3: 400, energyUsageMwh: 40, energySavingsMwh: 90, renewableEnergyPct: 70 },
    products: [],
  },
];
