import type { Project } from './types';
import { scoreProject, PILLARS } from './scoring';
import { circularBenefit } from './scoring';

export interface Recommendation {
  title: string;
  description: string;
  pillar: string;
  strategy: string;
  scoreGain: number;
  financialImpact: number;
  difficulty: 'Low' | 'Medium' | 'High';
  priority: 'Critical' | 'High' | 'Medium';
}

/**
 * Recommendations are generated by re-running the score engine against a
 * mutated copy of the project, so the "estimated score gain" shown to the user
 * is the actual delta the engine would produce, never a guessed number.
 */
function delta(p: Project, mutate: (draft: Project) => void): number {
  const draft: Project = structuredClone(p);
  mutate(draft);
  return scoreProject(draft).overall - scoreProject(p).overall;
}

export function recommendations(p: Project): Recommendation[] {
  const out: Recommendation[] = [];
  const base = circularBenefit(p);
  const wasteTotal = p.waste.manufacturingWasteKg + p.waste.packagingWasteKg;

  const push = (r: Recommendation) => { if (r.scoreGain > 0.05) out.push(r); };

  if (p.materials.recycledPct < 60) {
    const target = Math.min(100, p.materials.recycledPct + 25);
    push({
      title: `Raise recycled content to ${target}%`,
      description: `Recycled content is ${p.materials.recycledPct}% and carries the heaviest weight inside the materials pillar. Qualifying a recycled or reprocessed feedstock for the non-critical fraction is the single cheapest score move available.`,
      pillar: 'Materials Circularity',
      strategy: 'Narrow the loop — substitute virgin input',
      scoreGain: delta(p, (d) => { d.materials.recycledPct = target; }),
      financialImpact: p.financials.materialCost * 0.12,
      difficulty: 'Medium',
      priority: p.materials.recycledPct < 25 ? 'Critical' : 'High',
    });
  }

  if (p.waste.landfillKg > wasteTotal * 0.15) {
    const moved = p.waste.landfillKg * 0.6;
    push({
      title: 'Divert landfill stream into internal reuse',
      description: `${Math.round(p.waste.landfillKg)} kg/yr currently goes to landfill. Regrinding and re-feeding the clean fraction back into production removes both a disposal fee and an equivalent purchase of virgin material.`,
      pillar: 'Waste Management',
      strategy: 'Close the loop — internal reuse',
      scoreGain: delta(p, (d) => {
        d.waste.landfillKg -= moved;
        d.waste.reusedInternallyKg += moved;
      }),
      financialImpact: p.financials.wasteDisposalCost * 0.6 + p.financials.materialCost * 0.05,
      difficulty: 'Low',
      priority: 'Critical',
    });
  }

  if (!p.lifecycle.takeBackProgram) {
    push({
      title: 'Launch a take-back / collection programme',
      description: 'No collection route exists today, which caps the end-of-life recovery pillar. A take-back route also converts end-of-life units from a cost into a recovered-material revenue line.',
      pillar: 'End-of-Life Recovery',
      strategy: 'Close the loop — reverse logistics',
      scoreGain: delta(p, (d) => {
        d.lifecycle.takeBackProgram = true;
        d.lifecycle.recoveryRatePct = Math.min(100, d.lifecycle.recoveryRatePct + 20);
      }),
      financialImpact: base * 0.18,
      difficulty: 'High',
      priority: 'High',
    });
  }

  if (p.lifecycle.repairability < 70 || p.lifecycle.modularity < 70) {
    push({
      title: 'Design for disassembly and repair',
      description: 'Replacing bonded or welded joints with reversible fasteners raises repairability and modularity together, and extends the service life the lifecycle pillar is measured against.',
      pillar: 'Product Lifecycle',
      strategy: 'Slow the loop — extend product life',
      scoreGain: delta(p, (d) => {
        d.lifecycle.repairability = Math.min(100, d.lifecycle.repairability + 20);
        d.lifecycle.modularity = Math.min(100, d.lifecycle.modularity + 20);
        d.lifecycle.expectedLifeYears += 2;
      }),
      financialImpact: base * 0.1,
      difficulty: 'Medium',
      priority: 'Medium',
    });
  }

  if (p.environmental.renewableEnergyPct < 70) {
    push({
      title: `Move process energy to ${Math.min(100, p.environmental.renewableEnergyPct + 30)}% renewable`,
      description: 'Process energy is the fastest-moving lever in the environmental pillar and is usually a contracting decision rather than an engineering one.',
      pillar: 'Environmental Performance',
      strategy: 'Regenerate — clean energy input',
      scoreGain: delta(p, (d) => {
        d.environmental.renewableEnergyPct = Math.min(100, d.environmental.renewableEnergyPct + 30);
        d.environmental.carbonReductionTco2e *= 1.25;
      }),
      financialImpact: 0,
      difficulty: 'Low',
      priority: 'Medium',
    });
  }

  if (p.materials.bioBasedPct < 40 && p.materials.renewablePct < 60) {
    push({
      title: 'Qualify a bio-based or renewable feedstock',
      description: 'A bio-based substitution for the highest-volume component lifts two materials terms at once and de-risks exposure to fossil-linked resin pricing.',
      pillar: 'Materials Circularity',
      strategy: 'Regenerate — renewable input',
      scoreGain: delta(p, (d) => {
        d.materials.bioBasedPct = Math.min(100, d.materials.bioBasedPct + 25);
        d.materials.renewablePct = Math.min(100, d.materials.renewablePct + 20);
      }),
      financialImpact: -p.financials.materialCost * 0.04,
      difficulty: 'High',
      priority: 'Medium',
    });
  }

  return out.sort((a, b) => b.scoreGain - a.scoreGain);
}

export function headroom(p: Project) {
  const s = scoreProject(p);
  return PILLARS.map((def) => {
    const actual = s.pillars.find((x) => x.id === def.id)!;
    return {
      label: def.label,
      lost: Math.round((100 - actual.score) * def.weight * 10) / 10,
      score: actual.score,
    };
  }).sort((a, b) => b.lost - a.lost);
}
